---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: teps-lint
  namespace: tektonci
  description: |
    Lint teps and tep table
spec:
  params:
  - name: teps-folder
    description: The folders to lint with teps.py
  resources:
    inputs:
      - name: source
        type: git
  steps:
  - name: teps-validate
    image: gcr.io/tekton-releases/dogfooding/teps:latest
    args: ['validate', '--teps-folder', '$(resources.inputs.source.path)/$(params.teps-folder)']
  - name: teps-table-refresh
    image: gcr.io/tekton-releases/dogfooding/teps:latest
    workingDir: $(resources.inputs.source.path)
    args: ['table', '--teps-folder', '$(resources.inputs.source.path)/$(params.teps-folder)']
  - name: teps-table
    image: alpine/git:latest
    workingDir: $(resources.inputs.source.path)
    args: ['diff', '--exit-code', '$(params.teps-folder)/README.md']
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: teps-linter
  namespace: tektonci
spec:
  params:
    - name: gitCloneDepth
      description: Number of commits in the change + 1
    - name: fileFilterRegex
      description: Names regex to be matched in the list of modified files
    - name: checkName
      description: The name of the GitHub check that this pipeline is used for
    - name: gitHubCommand
      description: The command that was used to trigger testing
    - name: teps-folder
      description: The folder that hold the teps
  resources:
    - name: source
      type: git
  tasks:
  - name: teps-lint
    conditions:
    - conditionRef: "check-git-files-changed"
      params:
      - name: gitCloneDepth
        value: $(params.gitCloneDepth)
      - name: regex
        value: $(params.fileFilterRegex)
      resources:
      - name: source
        resource: source
    - conditionRef: "check-name-matches"
      params:
      - name: gitHubCommand
        value: $(params.gitHubCommand)
      - name: checkName
        value: $(params.checkName)
    taskRef:
      name: teps-lint
    params:
    - name: teps-folder
      value: $(params.teps-folder)
    resources:
      inputs:
      - name: source
        resource: source
